export const translations = {
  vi: {
    // --- Navigation & Menu ---
    home: "Trang chủ",
    allProducts: "Tất cả sản phẩm",
    searchPlaceholder: "Tìm kiếm sản phẩm...",
    searchBtn: "Tìm kiếm",
    hello: "Xin chào",
    profile: "Hồ sơ",
    admin: "Quản trị",
    voucher: "Voucher",
    orders: "Đơn hàng",
    logout: "Đăng xuất",
    login: "Đăng nhập",
    supermarket: "Siêu Thị Thực Phẩm Sạch",

    // --- Categories ---
    nguCoc: "Ngũ Cốc",
    banhMi: "Bánh Mì",
    suaTrung: "Sữa & Trứng",
    thit: "Thịt",
    haiSan: "Hải Sản",
    rauCu: "Rau Củ",
    traiCay: "Trái Cây",
    doUong: "Đồ Uống",

    // --- Home ---
    heroBadge: "🌿 Tươi mỗi ngày - Giao tận nhà",
    heroTitle: "Thực Phẩm Tươi Sạch Cho Gia Đình Bạn",
    heroSub: "Cung cấp nguồn thực phẩm hữu cơ, tươi sạch và an toàn nhất cho bữa ăn hàng ngày của bạn.",
    shopNow: "Mua ngay",
    freshFruits: "Trái cây tươi",
    explore: "KHÁM PHÁ",
    categoryTitle: "Danh mục sản phẩm",
    featuredTag: "NỔI BẬT",
    featuredTitle: "Sản phẩm nổi bật",
    viewAll: "Xem tất cả",
    hotDeal: "HOT DEAL",
    freshSeafood: "Hải Sản Sạch",
    organicVeggies: "Rau Củ Sạch",
    
    // --- Promos ---
    freeShip: "Miễn phí giao hàng",
    freeShipSub: "Đơn từ 200.000đ",
    qualityPromise: "Cam kết tươi sạch",
    qualitySub: "100% chất lượng",
    easyReturn: "Đổi trả dễ dàng",
    returnSub: "Trong vòng 24 giờ",
    securePay: "Thanh toán an toàn",
    securePaySub: "COD & Online",

    // --- Products & Filters ---
    search: "Tìm kiếm...",
    sortBy: "Sắp xếp",
    titleAZ: "Từ A - Z",
    titleZA: "Từ Z - A",
    priceLow: "Giá: Thấp - Cao",
    priceHigh: "Giá: Cao - Thấp",
    priceRange: "💰 Giá:",
    noProduct: "Không tìm thấy sản phẩm",
    almostOut: "Sắp hết",
    stockLeft: "Còn",
    addCart: "Thêm vào giỏ",
    buyNow: "Mua ngay",
    detail: "Chi tiết",
    quickView: "Xem nhanh",
    reviews: "đánh giá",

    // --- Cart ---
    yourCart: "Giỏ Hàng Của Bạn",
    emptyCart: "Giỏ hàng trống",
    emptyCartSub: "Hãy thêm sản phẩm vào giỏ hàng nhé!",
    startShopping: "Bắt đầu mua sắm",
    buyMore: "Mua thêm",
    toGetFreeShip: "để được miễn phí giao hàng!",
    orderSummary: "Tóm tắt đơn hàng",
    quantity: "Số lượng",
    subtotal: "Tạm tính",
    shippingFee: "Phí giao hàng",
    free: "Miễn phí",
    total: "Tổng cộng",
    proceedCheckout: "Tiến hành thanh toán",
    continueShopping: "Tiếp tục mua sắm",
    safeCheckout: "Thanh toán an toàn & bảo mật",

    // --- Checkout ---
    checkout: "Thanh Toán",
    shippingAddress: "Địa chỉ giao hàng",
    addressProfile: "Địa chỉ từ hồ sơ",
    savedAddresses: "Địa chỉ đã lưu",
    addNewAddress: "Thêm địa chỉ mới",
    deliveryInfo: "Thông tin giao hàng",
    orderNote: "Ghi chú đơn hàng",
    paymentMethod: "Phương thức thanh toán",
    cod: "Thanh toán khi nhận hàng (COD)",
    codSub: "An toàn, không phí phát sinh",
    apply: "Áp dụng",
    confirmOrder: "Xác nhận đặt hàng",
    backToCart: "Quay lại giỏ hàng",
    orderSuccess: "Đặt hàng thành công!",
    orderId: "Mã đơn hàng",

    // --- Order Status ---
    statusConfirmed: "Đã xác nhận",
    statusShipping: "Đang giao",
    statusDelivered: "Đã nhận",
    statusCancelled: "Đã hủy",

    // --- Admin ---
    dashboard: "Dashboard",
    orderManagement: "Quản lý Đơn hàng",
    productManagement: "Quản lý Sản phẩm",
    categoryManagement: "Quản lý Danh mục",
    totalRevenue: "Tổng doanh thu",
    totalOrders: "Tổng đơn hàng",
    lowStockItems: "Sản phẩm sắp hết",
    revenueByCat: "Doanh thu theo danh mục",
    ordersByStatus: "Đơn hàng theo trạng thái",
    recentOrders: "Đơn hàng gần đây",
    action: "Thao tác",
    edit: "Sửa",
    delete: "Xóa",
    save: "Lưu",
    cancel: "Hủy",
  },
  en: {
    // --- Navigation & Menu ---
    home: "Home",
    allProducts: "All Products",
    searchPlaceholder: "Search for products...",
    searchBtn: "Search",
    hello: "Hello",
    profile: "Profile",
    admin: "Admin",
    voucher: "Vouchers",
    orders: "Orders",
    logout: "Logout",
    login: "Login",
    supermarket: "Fresh Food Supermarket",

    // --- Categories ---
    nguCoc: "Cereals & Grains",
    banhMi: "Bakery",
    suaTrung: "Dairy & Eggs",
    thit: "Meat",
    haiSan: "Seafood",
    rauCu: "Vegetables",
    traiCay: "Fruits",
    doUong: "Beverages",

    // --- Home ---
    heroBadge: "🌿 Fresh Everyday - Home Delivery",
    heroTitle: "Fresh & Clean Food For Your Family",
    heroSub: "Providing the most organic, fresh, and safe food for your daily meals.",
    shopNow: "Shop Now",
    freshFruits: "Fresh Fruits",
    explore: "EXPLORE",
    categoryTitle: "Categories",
    featuredTag: "FEATURED",
    featuredTitle: "Featured Products",
    viewAll: "View All",
    hotDeal: "HOT DEAL",
    freshSeafood: "Fresh Seafood",
    organicVeggies: "Organic Veggies",

    // --- Promos ---
    freeShip: "Free Shipping",
    freeShipSub: "Orders over 200k",
    qualityPromise: "Freshness Guaranteed",
    qualitySub: "100% Quality",
    easyReturn: "Easy Returns",
    returnSub: "Within 24 hours",
    securePay: "Secure Payment",
    securePaySub: "COD & Online",

    // --- Products & Filters ---
    search: "Search...",
    sortBy: "Sort by",
    titleAZ: "A - Z",
    titleZA: "Z - A",
    priceLow: "Price: Low to High",
    priceHigh: "Price: High to Low",
    priceRange: "💰 Price:",
    noProduct: "No products found",
    almostOut: "Low Stock",
    stockLeft: "Left",
    addCart: "Add to Cart",
    buyNow: "Buy Now",
    detail: "Details",
    quickView: "Quick View",
    reviews: "reviews",

    // --- Cart ---
    yourCart: "Your Cart",
    emptyCart: "Cart is empty",
    emptyCartSub: "Let's add some products to your cart!",
    startShopping: "Start shopping",
    buyMore: "Spend",
    toGetFreeShip: "more to get free shipping!",
    orderSummary: "Order Summary",
    quantity: "Quantity",
    subtotal: "Subtotal",
    shippingFee: "Shipping Fee",
    free: "Free",
    total: "Total",
    proceedCheckout: "Proceed to Checkout",
    continueShopping: "Continue Shopping",
    safeCheckout: "Safe & Secure Payment",

    // --- Checkout ---
    checkout: "Checkout",
    shippingAddress: "Shipping Address",
    addressProfile: "Address from profile",
    savedAddresses: "Saved Addresses",
    addNewAddress: "Add new address",
    deliveryInfo: "Delivery Information",
    orderNote: "Order Notes",
    paymentMethod: "Payment Method",
    cod: "Cash on Delivery (COD)",
    codSub: "Safe, no hidden fees",
    apply: "Apply",
    confirmOrder: "Confirm Order",
    backToCart: "Back to Cart",
    orderSuccess: "Order placed successfully!",
    orderId: "Order ID",

    // --- Order Status ---
    statusConfirmed: "Confirmed",
    statusShipping: "Shipping",
    statusDelivered: "Delivered",
    statusCancelled: "Cancelled",

    // --- Admin ---
    dashboard: "Dashboard",
    orderManagement: "Order Management",
    productManagement: "Product Management",
    categoryManagement: "Category Management",
    totalRevenue: "Total Revenue",
    totalOrders: "Total Orders",
    lowStockItems: "Low Stock Items",
    revenueByCat: "Revenue by Category",
    ordersByStatus: "Orders by Status",
    recentOrders: "Recent Orders",
    action: "Action",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
  }
};