import { createContext, useContext, useState } from "react";

const LangContext = createContext();

export const translations = {
  vi: {
    // Menu
    home: "Trang Chủ",
    allProducts: "Tất Cả SP",
    cart: "Giỏ hàng",
    cartItems: "sản phẩm",
    hello: "Xin chào",
    logout: "Đăng xuất",
    login: "Đăng nhập",
    searchPlaceholder: "Tìm kiếm thực phẩm...",
    // Categories
    nguCoc: "Ngũ Cốc",
    banhMi: "Bánh Mì",
    suaTrung: "Sữa & Trứng",
    thit: "Thịt",
    haiSan: "Hải Sản",
    rauCu: "Rau Củ",
    traiCay: "Trái Cây",
    // Home
    heroTitle: "🛒 Siêu Thị Thực Phẩm Online",
    heroSub: "Thực phẩm tươi sạch, giao tận nhà nhanh chóng",
    shopNow: "Mua Sắm Ngay →",
    categoryTitle: "📦 Danh Mục Sản Phẩm",
    featuredTitle: "⭐ Sản Phẩm Nổi Bật",
    viewAll: "Xem tất cả →",
    freeShip: "🚚 Miễn phí giao hàng",
    freeShipSub: "Cho đơn hàng từ 200.000đ",
    freshGuarantee: "✅ Cam kết tươi sạch",
    freshSub: "100% thực phẩm chất lượng",
    easyReturn: "🔄 Đổi trả dễ dàng",
    easyReturnSub: "Trong vòng 24 giờ",
    // Product
    search: "🔍 Tìm kiếm sản phẩm...",
    sortBy: "-- Sắp xếp --",
    titleAZ: "Tên A → Z",
    titleZA: "Tên Z → A",
    priceLow: "Giá thấp → cao",
    priceHigh: "Giá cao → thấp",
    results: "sản phẩm",
    noProduct: "Không tìm thấy sản phẩm nào",
    almostOut: "Sắp hết!",
    addCart: "+ Giỏ hàng",
    detail: "Chi tiết",
    remain: "Còn",
    reviews: "đánh giá",
    // Detail
    notFound: "Không tìm thấy sản phẩm",
    backHome: "← Về trang chủ",
    category: "Danh mục",
    stock: "Tồn kho",
    inStock: "Còn sản phẩm",
    outOfStock: "Hết hàng",
    addToCart: "🛒 Thêm vào giỏ hàng",
    buyNow: "⚡ Mua ngay",
    addedToCart: "✅ Đã thêm vào giỏ hàng!",
    writeReview: "✍️ Viết đánh giá",
    yourName: "Tên của bạn",
    reviewContent: "Nội dung đánh giá...",
    submitReview: "Gửi đánh giá",
    customerReviews: "💬 Đánh giá từ khách hàng",
    noReview: "Chưa có đánh giá nào. Hãy là người đầu tiên!",
    // Cart
    cartTitle: "🛒 Giỏ Hàng Của Bạn",
    emptyCart: "Giỏ hàng trống",
    emptyCartSub: "Hãy thêm sản phẩm vào giỏ hàng",
    continueShopping: "🏪 Tiếp tục mua sắm",
    orderSummary: "📋 Tóm tắt đơn hàng",
    subtotal: "Tạm tính:",
    shipping: "Phí giao hàng:",
    freeShipping: "Miễn phí",
    total: "Tổng cộng:",
    checkout: "💳 Tiến hành thanh toán",
    freeShipNote: "Mua thêm để được miễn phí giao hàng!",
    deleteItem: "🗑️ Xóa",
    // Checkout
    checkoutTitle: "💳 Thanh Toán",
    shippingInfo: "📦 Thông tin giao hàng",
    fullName: "Họ và tên *",
    phone: "Số điện thoại *",
    address: "Địa chỉ giao hàng *",
    note: "Ghi chú",
    notePlaceholder: "Ghi chú cho đơn hàng (không bắt buộc)",
    paymentMethod: "💵 Phương thức thanh toán",
    cod: "💵 Thanh toán khi nhận hàng (COD)",
    yourOrder: "🧾 Đơn hàng của bạn",
    confirmOrder: "✅ Xác nhận đặt hàng",
    backToCart: "← Quay lại giỏ hàng",
    fillInfo: "Vui lòng điền đầy đủ thông tin!",
    orderSuccess: "Đặt hàng thành công!",
    thankYou: "Cảm ơn bạn đã mua sắm tại FoodMart.",
    deliveryTime: "Đơn hàng sẽ được giao trong 2-4 giờ.",
    redirecting: "Đang chuyển về trang chủ...",
    // Login
    loginTitle: "Đăng Nhập",
    registerTitle: "Đăng Ký",
    emailLabel: "📧 Email",
    passwordLabel: "🔒 Mật khẩu",
    nameLabel: "👤 Họ và tên",
    loginBtn: "🔑 Đăng Nhập",
    registerBtn: "✅ Đăng Ký",
    noAccount: "Chưa có tài khoản? ",
    hasAccount: "Đã có tài khoản? ",
    registerNow: "Đăng ký ngay",
    loginNow: "Đăng nhập",
    demoAccount: "🧪 Tài khoản demo:",
    useDemo: "Dùng tài khoản demo",
    wrongLogin: "Email hoặc mật khẩu không đúng!",
    emailUsed: "Email đã được sử dụng!",
    fillAll: "Vui lòng điền đầy đủ thông tin!",
    enterName: "Vui lòng nhập họ tên!",
  },

  en: {
    // Menu
    home: "Home",
    allProducts: "All Products",
    cart: "Cart",
    cartItems: "items",
    hello: "Hello",
    logout: "Logout",
    login: "Login",
    searchPlaceholder: "Search for food...",
    // Categories
    nguCoc: "Grains",
    banhMi: "Bakery",
    suaTrung: "Dairy & Eggs",
    thit: "Meat",
    haiSan: "Seafood",
    rauCu: "Vegetables",
    traiCay: "Fruits",
    // Home
    heroTitle: "🛒 FoodMart Online Supermarket",
    heroSub: "Fresh food, delivered fast to your door",
    shopNow: "Shop Now →",
    categoryTitle: "📦 Product Categories",
    featuredTitle: "⭐ Featured Products",
    viewAll: "View all →",
    freeShip: "🚚 Free Shipping",
    freeShipSub: "For orders over 200,000đ",
    freshGuarantee: "✅ Fresh Guarantee",
    freshSub: "100% quality food",
    easyReturn: "🔄 Easy Returns",
    easyReturnSub: "Within 24 hours",
    // Product
    search: "🔍 Search products...",
    sortBy: "-- Sort By --",
    titleAZ: "Name A → Z",
    titleZA: "Name Z → A",
    priceLow: "Price Low → High",
    priceHigh: "Price High → Low",
    results: "products",
    noProduct: "No products found",
    almostOut: "Almost out!",
    addCart: "+ Add to Cart",
    detail: "Detail",
    remain: "Left",
    reviews: "reviews",
    // Detail
    notFound: "Product not found",
    backHome: "← Back to home",
    category: "Category",
    stock: "Stock",
    inStock: "In Stock",
    outOfStock: "Out of Stock",
    addToCart: "🛒 Add to Cart",
    buyNow: "⚡ Buy Now",
    addedToCart: "✅ Added to cart!",
    writeReview: "✍️ Write a Review",
    yourName: "Your name",
    reviewContent: "Review content...",
    submitReview: "Submit Review",
    customerReviews: "💬 Customer Reviews",
    noReview: "No reviews yet. Be the first!",
    // Cart
    cartTitle: "🛒 Your Shopping Cart",
    emptyCart: "Your cart is empty",
    emptyCartSub: "Add some products to your cart",
    continueShopping: "🏪 Continue Shopping",
    orderSummary: "📋 Order Summary",
    subtotal: "Subtotal:",
    shipping: "Shipping:",
    freeShipping: "Free",
    total: "Total:",
    checkout: "💳 Proceed to Checkout",
    freeShipNote: "Add more to get free shipping!",
    deleteItem: "🗑️ Remove",
    // Checkout
    checkoutTitle: "💳 Checkout",
    shippingInfo: "📦 Shipping Information",
    fullName: "Full Name *",
    phone: "Phone Number *",
    address: "Shipping Address *",
    note: "Note",
    notePlaceholder: "Order note (optional)",
    paymentMethod: "💵 Payment Method",
    cod: "💵 Cash on Delivery (COD)",
    yourOrder: "🧾 Your Order",
    confirmOrder: "✅ Confirm Order",
    backToCart: "← Back to Cart",
    fillInfo: "Please fill in all required fields!",
    orderSuccess: "Order Placed Successfully!",
    thankYou: "Thank you for shopping at FoodMart.",
    deliveryTime: "Your order will be delivered in 2-4 hours.",
    redirecting: "Redirecting to home...",
    // Login
    loginTitle: "Login",
    registerTitle: "Register",
    emailLabel: "📧 Email",
    passwordLabel: "🔒 Password",
    nameLabel: "👤 Full Name",
    loginBtn: "🔑 Login",
    registerBtn: "✅ Register",
    noAccount: "Don't have an account? ",
    hasAccount: "Already have an account? ",
    registerNow: "Register now",
    loginNow: "Login",
    demoAccount: "🧪 Demo account:",
    useDemo: "Use demo account",
    wrongLogin: "Incorrect email or password!",
    emailUsed: "Email already in use!",
    fillAll: "Please fill in all fields!",
    enterName: "Please enter your name!",
  },
};

export function LangProvider({ children }) {
  const [lang, setLang] = useState("vi");
  const t = translations[lang];
  const toggleLang = () => setLang((prev) => (prev === "vi" ? "en" : "vi"));

  return (
    <LangContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}